-- MySQL Script generated by MySQL Workbench
-- Mon May 22 13:44:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE DATABASE GestionFarmacia;

Use GestionFarmacia;

-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestionFarmacia`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NULL,
  `tipoProducto` VARCHAR(60) NULL,
  `precio` FLOAT NULL,
  `fechaCaducidad` DATE NULL,
  `esControlado` VARCHAR(10) NULL,
  `stock` INT NULL,
  `fotoProducto` MEDIUMBLOB NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`InventarioProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestionFarmacia`.`InventarioProducto` (
  `idInventarioProducto` INT NOT NULL,
  `idProducto` INT NOT NULL,
  PRIMARY KEY (`idInventarioProducto`, `idProducto`),
  FOREIGN KEY (`idProducto`) REFERENCES `Producto` (`idProducto`)
) ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `mydb`.`Sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestionFarmacia`.`Sede` (
  `idSede` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NULL,
  `direccion` VARCHAR(225) NULL,
  `ciudad` VARCHAR(225) NULL,
  `InventarioProducto_idInventarioProducto` INT NOT NULL,
  PRIMARY KEY (`idSede`),
  INDEX `fk_Sede_InventarioProducto1_idx` (`InventarioProducto_idInventarioProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Sede_InventarioProducto1`
    FOREIGN KEY (`InventarioProducto_idInventarioProducto`)
    REFERENCES `GestionFarmacia`.`InventarioProducto` (`idInventarioProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestionFarmacia`.`Empleado` (
  `idEmpleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NULL,
  `apellidoPaterno` VARCHAR(60) NULL,
  `apellidoMaterno` VARCHAR(60) NULL,
  `correoElectronico` VARCHAR(100) NULL,
  `foto` MEDIUMBLOB NULL,
  `username` VARCHAR(60) NULL,
  `password` VARCHAR(60) NULL,
  `tipoEmpleado` VARCHAR(100) NULL,
  `Sede_idSede` INT NOT NULL,
  `Horario_idHorario` INT NOT NULL,
  PRIMARY KEY (`idEmpleado`),
  INDEX `fk_Empleado_Sede1_idx` (`Sede_idSede` ASC) VISIBLE,
  INDEX `fk_Empleado_Horario1_idx` (`Horario_idHorario` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_Sede1`
    FOREIGN KEY (`Sede_idSede`)
    REFERENCES `GestionFarmacia`.`Sede` (`idSede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_Empleado_Horario1`
    FOREIGN KEY (`Horario_idHorario`)
    REFERENCES `GestionFarmacia`.`Horario` (`idHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Promocion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestionFarmacia`.`Promocion` (
  `idPromociones` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(225) NULL,
  `descripcion` VARCHAR(225) NULL,
  `descuento` FLOAT NULL,
  `fechaInicio` DATE NULL,
  `fechaFin` DATE NULL,
  `fotoPromocion` MEDIUMBLOB NULL,
  `Producto_idProducto` INT NOT NULL,
  PRIMARY KEY (`idPromociones`),
  INDEX `fk_Promociones_Producto1_idx` (`Producto_idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Promociones_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `GestionFarmacia`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestionFarmacia`.`Venta` (
  `idVenta` INT NOT NULL AUTO_INCREMENT,
  `fechaVenta` DATE NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `fk_Venta_Empleado1_idx` (`Empleado_idEmpleado` ASC) VISIBLE,
  CONSTRAINT `fk_Venta_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `GestionFarmacia`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestionFarmacia`.`Proveedor` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `telefono` VARCHAR(20) NULL,
  `direccion` VARCHAR(100) NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestionFarmacia`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `fechaPedido` VARCHAR(45) NULL,
  `total` FLOAT NULL,
  `rastreo` VARCHAR(60) NULL,
  `fechaEnvio` DATE NULL,
  `direccion` VARCHAR(100) NULL,
  `Proveedor_idProveedor` INT NOT NULL,
  `Sede_idSede` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_Pedido_Proveedor1_idx` (`Proveedor_idProveedor` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Proveedor1`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `GestionFarmacia`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    INDEX `fk_Pedido_Sede1_idx` (`Sede_idSede` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Sede1`
    FOREIGN KEY (`Sede_idSede`)
    REFERENCES `GestionFarmacia`.`Sede` (`idSede`)
	ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Detalle_Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestionFarmacia`.`Detalle_Venta` (
  `Producto_idProducto` INT NOT NULL,
  `Venta_idVenta` INT NOT NULL,
  `cantidad` INT NULL,
  `total` FLOAT NULL,
  PRIMARY KEY (`Producto_idProducto`, `Venta_idVenta`),
  INDEX `fk_Producto_has_Venta_Venta1_idx` (`Venta_idVenta` ASC) VISIBLE,
  INDEX `fk_Producto_has_Venta_Producto1_idx` (`Producto_idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_has_Venta_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `GestionFarmacia`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_Venta_Venta1`
    FOREIGN KEY (`Venta_idVenta`)
    REFERENCES `GestionFarmacia`.`Venta` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestionFarmacia`.`Producto_Pedido` (
  `Producto_idProducto` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `cantidad` INT NULL,
  `total` FLOAT NULL,
  PRIMARY KEY (`Producto_idProducto`, `Pedido_idPedido`),
  INDEX `fk_Producto_has_Pedido_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  INDEX `fk_Producto_has_Pedido_Producto1_idx` (`Producto_idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_has_Pedido_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `GestionFarmacia`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `GestionFarmacia`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestionFarmacia`.`Horario` (
  `idHorario` INT NOT NULL AUTO_INCREMENT,
  `turno` VARCHAR(45) NULL,
  `horario` VARCHAR(45) NULL,
  PRIMARY KEY (`idHorario`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into `Producto`(
nombre, tipoProducto, precio, fechaCaducidad, esControlado, stock) values
('Paracetamol', 'Medicamento', 149.47, '2025-07-20', 'No', 4),
('Agua natural', 'Producto', 12.50, '2027-03-15', 'No', 6),
('Rastrillo desechable', 'Producto', 240.89, '2025-07-20', 'No', 3),
('Ibuprofeno', 'Medicamento', 35.33, '2024-04-24', 'No', 10),
('Amoxicilina', 'Medicamento', 233.00, '2026-03-30', 'No', 20),
('Cloxazolam', 'Medicamento', 80.00, '2024-10-13', 'Si', 7),
('Aceite', 'Producto', 38.50, '2024-06-20', 'No', 15),
('Jabon corporal', 'Producto', 18.90, '2027-11-23', 'No', 25),
('Diazepan', 'Medicamento', 174.00, '2026-06-11', 'Si', 5);
;

insert into `InventarioProducto`(
idInventarioProducto, idProducto)VALUES
(1,1),
(1,2),
(1,3),
(2,4),
(2,5),
(2,6),
(3,7),
(3,8),
(3,9)
;

insert into `Sede`(
nombre,direccion,ciudad,InventarioProducto_idInventarioProducto)VALUES
('Sede A','Calle Principal 123','Ciudad A',1),
('Sede B','Avenida Central 456','Ciudad B',2),
('Sede C','Boulevard Norte 789','Ciudad C',3)
;

insert into `Horario`(
turno, horario)VALUES
('Matutino','7:00-2:00'),
('Vespertino','2:00-9:00')
;

insert into `Empleado`(
nombre, apellidoPaterno, apellidoMaterno,correoElectronico, username, password, tipoEmpleado, Sede_idSede, Horario_idHorario)VALUES
('Juan','González','Rodríguez','juan_gonzalez@hotmail.com','juangonzalez','abcde12345','Administrador',1,1),
('María','López','García','maria_lopez@hotmail.com','marialopez','12345abcde','Encargado',2,2),
('Andrés','Ramírez','Jiménez','andres_ramirez@hotmail.com','andresramirez','qwerty12345','Administrador',3,1),
('Laura','Vargas','Martínez','laura_vargas@hotmail.com','lauravargas','123456','Encargado',1,2),
('Rene','Garcia','Velazquez','rene_ulises@hotmail.com','reneulises','rene12345','Administrador',3,1)
;

insert into `Proveedor`(
nombre, telefono, direccion)VALUES
('Maypo Distribuidora','+52 555-123-4567','Calle Juárez #123, Colonia Centro, Ciudad de México'),
('Distribuidora Farma','+52 333-987-6543','Avenida Hidalgo #456, Colonia Reforma, Guadalajara, Jalisco'),
('Medix','+52 662-876-5432','Calle Zaragoza #789, Colonia Centro, Monterrey, Nuevo León'),
('Distribuidora e Importadora Mexicana de Medicamentos (DIMM)','+52 811-234-5678','Avenida Revolución #321, Colonia Zona Norte, Tijuana, Baja California'),
('Distribuidora de Medicamentos e Insumos (DIMEIN)','+52 442-765-4321','Calle Morelos #567, Colonia Centro, Puebla, Puebla'),
('Distribuidora de Medicamentos Genéricos (DMG)','+52 229-876-5432','Avenida Insurgentes #890, Colonia Del Valle, Ciudad de México'),
('Distribuidora de Productos Farmacéuticos (Diprofarma)','+52 332-987-6543','Calle Madero #234, Colonia Centro, Mérida, Yucatán')
;

insert into `Pedido`(
fechaPedido, total, rastreo, fechaEnvio, direccion, Proveedor_idProveedor, Sede_idSede)values
('2023-05-28', 2558.01, 'En Camino', '2023-06-07', 'Boulevard Norte 789', 3, 3),
('2023-05-30', 3749.15, 'En Camino', '2023-06-14', 'Avenida Central 456', 6, 2),
('2023-05-30', 2683.30, 'En Camino', '2023-06-09', 'Calle Principal 123', 1, 1),
('2023-05-26', 572.50, 'Entregado', '2023-05-31', 'Calle Principal 123', 4, 1)
;

insert into `Producto_Pedido`(
Producto_idProducto, Pedido_idPedido, cantidad, total)VALUES 
(1,1,5,747.35),
(4,1,2,70.66),
(9,1,10,1740.00),
(1,2,10,1494.70),
(3,2,5,1204.45),
(2,2,20,250.00),
(6,2,10,800.00),
(4,3,10,353.30),
(5,3,10,2330.00),
(2,4,15,187.50),
(7,4,10,385.00)
;
